name: adb_graphics
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - astroid=2.3.2
  - attrs=19.3.0
  - backcall=0.1.0
  - basemap=1.2.1
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - curl=7.65.3
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.1
  - defusedxml=0.6.0
  - eccodes=2.14.1
  - entrypoints=0.3
  - expat=2.2.5
  - freetype=2.10.0
  - geos=3.7.2
  - gettext=0.19.8.1
  - glib=2.58.3
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=64.2
  - importlib_metadata=0.23
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jasper=1.900.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9c
  - jsonschema=3.1.1
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - lazy-object-proxy=1.4.2
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=8.0.1
  - libcurl=7.65.3
  - libcxx=9.0.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm8=8.0.1
  - libnetcdf=4.7.1
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.2
  - llvm-openmp=9.0.0
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - more-itertools=7.2.0
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - nspr=4.20
  - nss=3.47
  - numpy=1.17.3
  - openssl=1.1.1d
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - pygrib=2.0.4
  - pylint=2.4.3
  - pyparsing=2.4.3
  - pyproj=1.9.6
  - pyqt=5.12.3
  - pyrsistent=0.15.5
  - pyshp=2.1.0
  - python=3.7.3
  - python-dateutil=2.8.1
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qt=5.12.5
  - qtconsole=4.5.5
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=41.6.0
  - six=1.13.0
  - sqlite=3.30.1
  - terminado=0.8.2
  - testpath=0.4.4
  - tk=8.6.9
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
