name: pygraf
channels:
  - defaults
  - conda-forge
dependencies:
  - atomicwrites=1.3.0
  - bleach=3.1.4
  - ipykernel=5.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - notebook=6.0.3
  - pickleshare=0.7.5
  - _libgcc_mutex=0.1
  - appdirs=1.4.3
  - astroid=2.3.3
  - attrs=19.3.0
  - backcall=0.1.0
  - basemap=1.3.0
  - basemap-data-hires=1.2.1
  - boost-cpp=1.72.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2019.10.16
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.9.11
  - cffi=1.14.0
  - cfitsio=3.470
  - chardet=3.0.4
  - cryptography=2.9.2
  - curl=7.69.1
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.2
  - defusedxml=0.6.0
  - eccodes=2.17.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - freexl=1.0.5
  - g2clib=1.6.0
  - geos=3.8.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.64.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - hdf4=4.2.13
  - hdf5=1.10.5
  - hdfeos2=2.20
  - hdfeos5=5.1.16
  - icu=64.2
  - idna=2.9
  - importlib_metadata=0.23
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jasper=1.900.1
  - jedi=0.15.1
  - jinja2=2.11.2
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.1.1
  - jupyter=1.0.0
  - jupyter_core=4.6.1
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.34
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.69.1
  - libdap4=3.20.6
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgdal=3.0.4
  - libgfortran-ng=7.5.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.16
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mccabe=0.6.1
  - metpy=0.12.1
  - mistune=0.8.4
  - more-itertools=7.2.0
  - ncurses=6.1
  - numpy=1.18.4
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - owslib=0.19.2
  - packaging=20.4
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.7.0
  - pillow=6.2.1
  - pint=0.11
  - pip=19.3.1
  - pixman=0.38.0
  - pluggy=0.13.0
  - pooch=1.1.1
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=7.0.0
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pyepsg=0.4.0
  - pygments=2.6.1
  - pygrib=2.0.4
  - pykdtree=1.3.1
  - pylint=2.4.4
  - pynio=1.5.5
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.12.3
  - pyrsistent=0.15.5
  - pyshp=2.1.0
  - pysocks=1.7.1
  - pytest=5.2.4
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=18.1.0
  - qt=5.12.5
  - qtconsole=4.6.0
  - readline=8.0
  - requests=2.23.0
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=41.6.0
  - shapely=1.7.0
  - six=1.15.0
  - sqlite=3.30.1
  - tbb=2018.0.5
  - terminado=0.8.2
  - testpath=0.4.4
  - tiledb=1.7.7
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - tzcode=2020a
  - urllib3=1.25.9
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - wrapt=1.11.2
  - xarray=0.15.1
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.4
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - ipywidgets=7.5.1
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - prompt-toolkit=3.0.5
  - widgetsnbextension=3.5.1
  - nspr=4.25
  - nss=3.47
  - py=1.8.1
  - pip:
    - pyqt5==5.12.3
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
